kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: registry
  namespace: {{ template }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      app: registry
